### ISSUE TITLE
ng4 - "export 'ResourceMethod' was not found in 'ngx-resource'

### ISSUE THREAD

**Issue by jpordonez** [troyanskiy/ng2-resource-rest#96] opened 2017-03-30 23:08 UTC
Hello, I am migrating my project to ng4 and when compiling my solution I get the following warning
./src/app/core/seguridad/recurso/AplicacionRecurso.ts
33:50-64 "export 'ResourceMethod' was not found in 'ngx-resource',
However everything works ok.

**Comment by brunonm** [comment] 2017-03-31 19:29
Same problem here.

**Comment by troyanskiy** [comment] 2017-04-02 08:37
Hello.
Could you please provide more details.
I can't reproduce that with Ionic2 nor [angular-seed](https://github.com/mgechev/angular-seed)

**Comment by midhunadarvin** [comment] 2017-04-02 17:25
Hi,
I am getting the same warning when i try to import it into my class. I'm not too familiar with the codebase but checking index.js file, i can only see the following exports.

```
export * from './src/Resource';
export * from './src/ResourceAction';
export * from './src/ResourceCRUD';
export * from './src/ResourceCRUDBase';
export * from './src/ResourceGlobalConfig';
export * from './src/ResourceModel';
export * from './src/ResourceParams';
export * from './src/ResourceProviders';
...
export { ResourceModule };
```

I cannot see a 'ResourceMethod' method. I am using ngx-resource version 2.0.5 . However my requests work fine. I am only getting this warning in my browser console for wherever i have used ResourceMethod Type.

**Comment by midhunadarvin** [comment] 2017-04-02 17:53
I was able to remove the warning by adding the line given below : 
`import {ResourceMethod} from 'ngx-resource/src/Interfaces';`

I think it is because the Interface ResourceMethod is not exported by the main export file. How about adding it in index.js . Also my typescript version is 2.2.1 .

**Comment by troyanskiy** [comment] 2017-04-02 18:35
@midhunadarvin Hello.
There is nothing to import in index.js file.
As you can see there is index.d.ts file with included Interfaces in it and the is also included into package.json
``` typescript
import { ModuleWithProviders } from '@angular/core';
export * from './src/Resource';
export * from './src/ResourceAction';
export * from './src/ResourceCRUD';
export * from './src/ResourceCRUDBase';
export * from './src/ResourceGlobalConfig';
export * from './src/ResourceModel';
export * from './src/ResourceParams';
export * from './src/ResourceProviders';
export * from './src/Interfaces';
export declare class ResourceModule {
    static forRoot(): ModuleWithProviders;
    static forChild(subSet: string): ModuleWithProviders;
}
```

As I wrote above I can't reproduce that with my projects so I need more details. The best will be to have a project with the error on github.

**Comment by jpordonez** [comment] 2017-04-03 15:09
Hello @troyanskiy 
This is my package.json file
{
  "name": "AppWeb",
  "version": "2.1.0",
  "license": "COMMERCIAL",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.0.1",
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
    "chart.js": "2.5.0",
    "core-js": "^2.4.1",
    "fullcalendar": "^3.3.0",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "nanoscroller": "0.8.7",
    "ng2-spin-kit": "^1.3.0",
    "ngx-resource": "^2.0.2",
    "primeng": "^4.0.0-rc.2",
    "quill": "^1.2.3",
    "rxjs": "^5.2.0",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "4.0.1",
    "@types/jasmine": "2.5.47",
    "@types/node": "^7.0.12",
    "codelyzer": "~3.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.0.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.1",
    "ts-node": "~3.0.2",
    "tslint": "~5.0.0",
    "typescript": "~2.2.2"
  }
}

This is my package.json file

import {Injectable} from '@angular/core';
import {Resource, ResourceParams, ResourceAction, ResourceMethod} from 'ngx-resource';
import {RequestMethod} from '@angular/http';
import {Resource} from 'ngx-resource';
import {BaseRecurso} from '../../../core/seguridad/recurso/BaseRecurso';
import {AppSettings} from '../../../core/constantes/app-settings';

@Injectable()
@ResourceParams({
  url: AppSettings.API_ENDPOINT,
  headers:{
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    withCredentials: false
  }

})
export class AvaluoParametrizacionRecurso extends Resource {

  @ResourceAction({
    method: RequestMethod.Post,
    path: 'AvaluoParametrizacion/Index'
  })
  listar: ResourceMethod<any, any[]>;

  @ResourceAction({
    method: RequestMethod.Post,
    path: 'AvaluoParametrizacion/Edit'
  })
  editar: ResourceMethod<any, any>;

  @ResourceAction({
	  method: RequestMethod.Get,
    isArray: true,
	  path: 'AvaluoParametrizacion/Get'
  })
  getDatosInicio: ResourceMethod<any, any>;

}

I attach this thread that can help you with the origin of the problem, it mentions that this happens when you export more than one interface in the same file in this case happens with "ngx-resource / src / Interfaces.ts"

https://github.com/angular/angular-cli/issues/2034

**having the same issue. (Works fine despite warning)
are you exporting more than one interface/class/const from the file?
issue stopped for me after i exported each interface from its own dedicated file.

meaning if i had one file with multiple exports - i got warnings in build (export 'MyInterface1' was not found in '../file')

    file.ts

    export interface MyInterface1 {}
    export interface MyInterface2 {}

after refactor - no warning

    file1.ts

    export interface MyInterface1 {}

    file2.ts

    export interface MyInterface2 {}**

**Comment by jpordonez** [comment] 2017-04-03 15:15
Hello @midhunadarvin 

import {ResourceMethod} from 'ngx-resource/src/Interfaces';

Remove the warning.

Thanks to you.

**Comment by cipchk** [comment] 2017-04-05 03:43
+1

**Comment by troyanskiy** [comment] 2017-04-05 06:38
Could you please provide project example (source code) so I can reproduce that?
Thank you.

**Comment by midhunadarvin** [comment] 2017-04-06 14:06
Here : https://github.com/midhunadarvin/Angular2-Full-Stack

Currently i have imported ResourceMethod from  'ngx-resource/src/Interfaces'. You will have to change it to just ngx-resource to see the warning. 

The File in which i have imported is in client/app/shared/resources/cat.resource.ts . Change it and just run ng serve .

**Comment by desfero** [comment] 2017-04-14 12:27
+1

**Comment by troyanskiy** [comment] 2017-04-14 20:15
Well... I can't reproduce that.
I've took https://github.com/midhunadarvin/Angular2-Full-Stack
`npm i`
and after
``` bash
$ npm run ng serve

> angular2-full-stack@4.0.0 ng /Users/troy/Downloads/Angular2-Full-Stack-master
> ng "serve"

** NG Live Development Server is running on http://localhost:4200 **
Hash: 41bc0d594c8b3bec54e7                                                              
Time: 9385ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 22.6 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 150 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 161 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.64 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
```

Strange that yesterday I saw the warnings, but after today's new installation I don't have the warnings anymore, probably some libs has been updated.

@midhunadarvin could you please remove your `node_modules` folder, execute `npm i` and retest `npm run ng serve` again to test?

@desfero could you please share your minimal code with the warning, so I can test it?

Thanks.

**Comment by troyanskiy** [comment] 2017-04-14 21:25
I have changes your `tsconfig module` from `es2015` to `commonjs` and the warning is gone.
Thanks to https://github.com/angular/angular-cli/issues/2034#issuecomment-293898804

**Comment by desfero** [comment] 2017-04-14 21:40
@troyanskiy works, thanks a lot for such quick response

**Comment by troyanskiy** [comment] 2017-04-14 21:41
@desfero you are welcome

**Comment by troyanskiy** [comment] 2017-04-25 18:37
Closing the issue.

**Closed by troyanskiy** 2017-04-25 18:37 UTC

**Comment by yamaha252** [comment] 2017-07-20 13:08
It is not a solution for this issue. I need exactly es2015 type, in another way some my external modules are crashing :(
Have any other suggestions to fix the warnings?

**Comment by deli6z** [comment] 2017-09-07 17:53
I have the same with 'ResourceMethodObservable'. I see that changing tsconfig module from es2015 to commonjs fixes it - but what change is actually doing? I assume ts is generating the project in a different way ?

**Comment by Prontsevich** [comment] 2017-10-10 19:49
Have the same issue with Angular CLI

**Comment by dbettini** [comment] 2017-10-17 17:27
@troyanskiy `es2015` is needed for tree shaking and AoT, isn't it?
